function plotTrajectories(sats)
%PLOTTRAJECTORIES Plot satellite trajectories generated by GMAT simulation.
%   Inputs: (dims),[units]
%    - sats; (nx(3m)),[km] array of position vectors, rows are time steps
%            and cols are (sat1.x sat1.y sat1.z sat2.x ...) OR
%            (nx3xm),[km] positions of m satellites over n time steps

if length(size(sats)) == 3      % option 2
    S = size(sats);
    sats = reshape(sats, [S(1) S(2)*S(3)]);
end

r = 1737.4;     % km, moon radius
n = size(sats, 2) / 3;

figure();
for i = 1:n
    j = (i-1)*3;    % set of coords
    plot3(sats(:,j+1), sats(:,j+2), sats(:,j+3), 'LineWidth', 2);
    hold on;
    scatter3(sats(end,j+1), sats(end,j+2), sats(end,j+3), 'ro', 'LineWidth', 2);
end
% plot3(x(1,1), x(2,1), x(3,1), 'go', 'LineWidth', 2);

% moon
[I, ~] = imread("lroc_color_poles_1k.jpg");
[xx, yy, zz] = ellipsoid(0, 0, 0, r, r, r);
globe = surf(xx, yy, -zz);
set(globe, 'FaceColor', 'texturemap', 'CData', I, 'FaceAlpha', 1, ...
    'EdgeColor', 'none');

hold off; grid on; axis equal;
xlabel("x (km)"); ylabel("y (km)"); zlabel("z (km)");
legend(["Orbit", "Satellite"], "location", "best");

end
